feat: Add watch command
mauricioabreu/golings pull request #4
Opened 2023-01-05 00:10 UTC by lalizita

Still building watch command

2023-03-08 17:21 UTC, mauricioabreu requested changes

2023-03-08 17:21 UTC, mauricioabreu commented on golings/cmd/watch.go
> +	file_path := fmt.Sprintf("%s/exercises", path)
This variable should be camelCase, like `filePath` except when you want them to be exported

2023-03-28 01:23 UTC, lalizita commented on golings/cmd/watch.go
> +				for {
good!

2023-03-28 01:25 UTC, lalizita commented on golings/cmd/watch.go
> +	defer watcher.Close()
I don't understand why I must not close the watcher, Could it make a memory lock problem happens?

2023-04-03 21:20 UTC, mauricioabreu approved these changes
Awesome! 🥇

2023-04-03 21:20 UTC, mauricioabreu commented
@lalizita want me to merge this?

2023-04-03 22:18 UTC, lalizita commented
yeah @mauricioabreu , should you merge it please?

2023-04-03 22:45 UTC, merged